spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/campus_ops_hub?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Mysql1602*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

app.frontend-url=http://localhost:5173

# OAuth2 Configuration - provide actual credentials for production
spring.security.oauth2.client.registration.google.client-id=486189954633-o98b0rjudug55482laidkap4qifmdcio.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}